apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.repository }}:{{ .Values.imageTag | default .Values.frontend.tag | default "latest" }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend-service:5000"
          ports:
            - containerPort: 80
