apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/{{ .Values.image.repositoryOwner }}/frontend:{{ default 'latest' .Values.imageTag }}"
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend-service:5000"
          ports:
            - containerPort: 80
